# Generated by Django 4.1.6 on 2023-02-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
